# Basic ESPHome device setup
esphome:
  name: opentherm                # Internal name of the device on the network
  friendly_name: OpenTherm       # Friendly name visible in Home Assistant

# Hardware configuration
esp32:
  board: esp32dev                # Specifies the ESP32 development board
  framework:
    type: arduino                # Uses Arduino framework (recommended for OpenTherm libs)

# External component for OpenTherm integration
external_components:
  source: github://ov1d1u/esphome-opentherm@main  # External OpenTherm component

# Enables logging over serial (for debugging)
logger:

# Enables native API for integration with Home Assistant
api:
  encryption:
    key: "rR4QfBRV9Qq7BWujlN4EgelqFdmk32CrvCOlhJRVvnA="  # Encryption key for secure communication

# Enables OTA firmware update via network
ota:
  - platform: esphome
    password: "8e324523d82a6077e7feea4eb6740837"  # Secure password for OTA updates

# Wi-Fi configuration
wifi:
  ssid: !secret wifi_ssid               # Wi-Fi SSID from secrets.yaml
  password: !secret wifi_password       # Wi-Fi password from secrets.yaml

  # Fallback Access Point in case Wi-Fi fails
  ap:
    ssid: "Opentherm Fallback Hotspot"
    password: "12345678"

# Captive portal for easy Wi-Fi configuration
captive_portal:

# OpenTherm hardware pin configuration
opentherm:
  in_pin: 21      # GPIO21 receives OpenTherm signal
  out_pin: 26     # GPIO26 sends OpenTherm signal

# OpenTherm sensors (read-only values from boiler)
sensor:
  - platform: opentherm
    t_dhw: { name: "DHW temperature (°C)" }                      # Domestic hot water temperature
    rel_mod_level: { name: "Relative modulation level (%)" }     # Modulation %
    ch_pressure: { name: "Water pressure in CH circuit (bar)" }  # Heating circuit pressure
    dhw_flow_rate: { name: "Water flow rate in DHW circuit (l/min)" } # DHW flow
    t_boiler: { name: "Boiler water temperature (°C)" }          # Boiler water temp
    t_exhaust: { name: "Boiler exhaust temperature (°C)" }       # Boiler flue gas temp
    t_dhw_set_ub: { name: "Upper bound for DHW setpoint (°C)" }
    t_dhw_set_lb: { name: "Lower bound for DHW setpoint (°C)" }
    max_t_set_ub: { name: "Upper bound for max CH setpoint (°C)" }
    max_t_set_lb: { name: "Lower bound for max CH setpoint (°C)" }
    t_dhw_set: { name: "DHW temperature setpoint (°C)" }
    max_t_set: { name: "Max CH water setpoint (°C)" }

# Binary sensors from OpenTherm protocol
binary_sensor:
  - platform: opentherm
    ch_active: { name: "Boiler Central Heating active" }     # CH mode active
    dhw_active: { name: "Boiler Domestic Hot Water active" } # DHW mode active
    flame_on: { name: "Boiler Flame on" }                    # Flame is on
    fault_indication:
      name: "Boiler Fault indication"                        # Boiler fault status
      entity_category: diagnostic
    diagnostic_indication:
      name: "Boiler Diagnostic event"                        # Diagnostic event
      entity_category: diagnostic

  # GPIO button (hardware input on GPIO35)
  - platform: gpio
    name: "Button #1"
    pin: GPIO35

# Number entity for writing setpoints to the boiler
number:
  - platform: opentherm
    t_set:
      id: t_set
      min_value: 20        # Min boiler setpoint
      max_value: 65        # Max boiler setpoint
      name: "Boiler Control setpoint"

# Relay and OpenTherm-based switches
switch:
  - platform: gpio
    pin: GPIO32            # Relay control pin
    name: "RELAY"

  - platform: opentherm
    ch_enable:
      name: "Boiler Central Heating enabled"
      restore_mode: RESTORE_DEFAULT_ON  # Retains state after restart

# Optional 1-Wire setup (commented out)
# one_wire:
#   - platform: gpio
#     pin: GPIO04
#     id: hub_1
#   - platform: gpio
#     pin: GPIO02
#     id: hub_2

# Optional Dallas temperature sensors (commented out)
# sensor:
#   - platform: dallas_temp
#     one_wire_id: hub_1
#     address: 0x6f7c86e908646128
#     name: "1-WIRE Dallas temperature BUS1"
#     update_interval: 60s
#   - platform: dallas_temp
#     one_wire_id: hub_2
#     address: 0xbc3c01d075cb5128
#     name: "1-WIRE Dallas temperature BUS2"
#     update_interval: 60s

# Status LED for visual indicator of device status
status_led:
  pin:
     number: GPIO33        # Status LED pin
     inverted: true        # LED is active LOW
