modbus_controller:
  - id: ${enm_id}
    address: ${enm_address}        # Modbus slave ID
    modbus_id: modbus_bus
    update_interval: 3s
    command_throttle: 50ms
    allow_duplicate_commands: false

# ===================== Discrete Inputs (FC02) =====================
# LEDs: 500..503 | Buttons: 520..523 | Relays: 540..541 | Alarms: 560..574 (ch*3+kind, ch=0..4)
binary_sensor:
  # --- LED physical states ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} LED1"
    address: 500
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} LED2"
    address: 501
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} LED3"
    address: 502
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} LED4"
    address: 503
    register_type: discrete_input

  # --- Buttons pressed ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} BTN1"
    address: 520
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} BTN2"
    address: 521
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} BTN3"
    address: 522
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} BTN4"
    address: 523
    register_type: discrete_input

  # --- Relay logical state ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Relay 1 State"
    address: 540
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Relay 2 State"
    address: 541
    register_type: discrete_input

  # --- Alarm active flags (kind: 0=Alarm,1=Warning,2=Event), ch: 0=L1,1=L2,2=L3,3=Total,4=CH_COUNT ---
  # L1 (560..562)
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L1 (Alarm)"
    address: 560
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L1 (Warning)"
    address: 561
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L1 (Event)"
    address: 562
    register_type: discrete_input

  # L2 (563..565)
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L2 (Alarm)"
    address: 563
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L2 (Warning)"
    address: 564
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L2 (Event)"
    address: 565
    register_type: discrete_input

  # L3 (566..568)
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L3 (Alarm)"
    address: 566
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L3 (Warning)"
    address: 567
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm L3 (Event)"
    address: 568
    register_type: discrete_input

  # Total (569..571)
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm Total (Alarm)"
    address: 569
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm Total (Warning)"
    address: 570
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Alarm Total (Event)"
    address: 571
    register_type: discrete_input


# ===================== Coils (FC01/05) =====================
# Relay coils are maintained (not pulses). Writes honored only if relay is in MODBUS mode and Button Override is OFF.
switch:
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Relay 1"
    address: 600
    register_type: coil
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Relay 2"
    address: 601
    register_type: coil

  # --- Alarm acknowledgements (write 1 to ACK; device auto-clears to 0) ---
  - platform: modbus_controller
    id: ${enm_id}_ack_l1
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} ACK L1"
    address: 610
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${enm_id}_ack_l1

  - platform: modbus_controller
    id: ${enm_id}_ack_l2
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} ACK L2"
    address: 611
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${enm_id}_ack_l2

  - platform: modbus_controller
    id: ${enm_id}_ack_l3
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} ACK L3"
    address: 612
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${enm_id}_ack_l3

  - platform: modbus_controller
    id: ${enm_id}_ack_total
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} ACK Total"
    address: 613
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${enm_id}_ack_total


# ===================== Sensors (FC04 Input Registers RO) =====================
# 32-bit values are high-word first in consecutive registers.
sensor:
  # --- RMS ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Urms L1"
    address: 100
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters: [{ multiply: 0.01 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Urms L2"
    address: 101
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters: [{ multiply: 0.01 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Urms L3"
    address: 102
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters: [{ multiply: 0.01 }]

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Irms L1"
    address: 110
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 3
    filters: [{ multiply: 0.001 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Irms L2"
    address: 111
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 3
    filters: [{ multiply: 0.001 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Irms L3"
    address: 112
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 3
    filters: [{ multiply: 0.001 }]

  # --- PF (×1000) & Angle (×0.1°) ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} PF L1"
    address: 240
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 3
    filters: [{ multiply: 0.001 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} PF L2"
    address: 241
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 3
    filters: [{ multiply: 0.001 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} PF L3"
    address: 242
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 3
    filters: [{ multiply: 0.001 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} PF Total"
    address: 243
    register_type: read
    value_type: S_WORD
    accuracy_decimals: 3
    filters: [{ multiply: 0.001 }]

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Angle L1"
    address: 244
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°"
    accuracy_decimals: 1
    filters: [{ multiply: 0.1 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Angle L2"
    address: 245
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°"
    accuracy_decimals: 1
    filters: [{ multiply: 0.1 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Angle L3"
    address: 246
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°"
    accuracy_decimals: 1
    filters: [{ multiply: 0.1 }]

  # --- Frequency & Temperature ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Line Frequency"
    address: 250
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
    filters: [{ multiply: 0.01 }]

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Temperature"
    address: 251
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"

  # --- P/Q/S (s32) ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} P L1"
    address: 200
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "W"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} P L2"
    address: 202
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "W"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} P L3"
    address: 204
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "W"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} P Total"
    address: 206
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "W"

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Q L1"
    address: 210
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "var"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Q L2"
    address: 212
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "var"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Q L3"
    address: 214
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "var"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Q Total"
    address: 216
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "var"

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} S L1"
    address: 220
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "VA"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} S L2"
    address: 222
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "VA"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} S L3"
    address: 224
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "VA"
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} S Total"
    address: 226
    register_type: read
    value_type: S_DWORD
    unit_of_measurement: "VA"

  # --- Energies (u32 Wh/varh/VAh) — Total Increasing ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} AP L1"
    address: 300
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} AP L2"
    address: 302
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} AP L3"
    address: 304
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} AP Total"
    address: 306
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} AN L1"
    address: 308
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} AN L2"
    address: 310
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} AN L3"
    address: 312
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} AN Total"
    address: 314
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "Wh"
    device_class: energy
    state_class: total_increasing

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} RP L1"
    address: 316
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "varh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} RP L2"
    address: 318
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "varh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} RP L3"
    address: 320
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "varh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} RP Total"
    address: 322
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "varh"
    state_class: total_increasing

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} RN L1"
    address: 324
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "varh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} RN L2"
    address: 326
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "varh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} RN L3"
    address: 328
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "varh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} RN Total"
    address: 330
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "varh"
    state_class: total_increasing

  # --- Apparent Energy (VAh) ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} VAh L1"
    address: 332
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "VAh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} VAh L2"
    address: 334
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "VAh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} VAh L3"
    address: 336
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "VAh"
    state_class: total_increasing
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} VAh Total"
    address: 338
    register_type: read
    value_type: U_DWORD
    unit_of_measurement: "VAh"
    state_class: total_increasing
