modbus_controller:
  - id: ${enm_id}
    address: ${enm_address}        # Modbus slave ID
    modbus_id: modbus_bus
    update_interval: 3s
    command_throttle: 50ms
    allow_duplicate_commands: false

# ===================== Discrete Inputs (FC02) =====================
# NEW MAP:
# LEDs: 0..3 | Buttons: 4..7 | Relays: 8..9 | Alarms: 16..27 (addr = 16 + ch*3 + kind, ch=0..3)



# ===================== Coils (FC01/05) =====================
# NEW MAP:
# Relay coils: 0..1
# Ack coils: 16..19 (write 1 to ACK; device auto-clears to 0)
switch:
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Relay 1"
    address: 0
    register_type: coil


# ===================== Sensors (FC04 Input Registers RO) =====================
# NEW MAP:
# Urms: 0..2 (0.01V) | Irms: 3..5 (0.001A)
# Freq: 6 (0.01Hz) | Temp: 7 (int16°C)
# PF raw: 8..11 (x0.001)
# P (s32): 20/22/24/26  | Q (s32): 28/30/32/34 | S (s32): 36/38/40/42
# Angles: 44..46 (0.1°)
# Energies (u32): base 60 (see below)
sensor:
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Urms L3"
    address: 2
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "V"
    accuracy_decimals: 2
    filters: [{ multiply: 0.01 }]
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Irms L1"
    address: 3
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "A"
    accuracy_decimals: 3
    filters: [{ multiply: 0.001 }]
  # --- Frequency & Temperature ---
  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Line Frequency"
    address: 6
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
    filters: [{ multiply: 0.01 }]

  - platform: modbus_controller
    modbus_controller_id: ${enm_id}
    name: "${enm_prefix} Temperature"
    address: 7
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"