# DIO-430-R1 — ESPHome Modbus map (package-friendly)
# Mirrors the firmware map in default_DIO_430_R1.ino
#
# Notes
# - Read-only states are exposed as `discrete_input` registers (FC=02)
#   • DI1..DI4 at 1..4
#   • Relay logical state R1..R3 at 60..62
#   • LED logical state LED1..LED3 at 90..92
# - Commands are *pulse* coils (FC=05/15): write TRUE momentarily; firmware auto-clears
#   • Relay ON  (R1..R3)  at 200..202
#   • Relay OFF (R1..R3)  at 210..212
#   • DI ENABLE (IN1..IN4) at 300..303
#   • DI DISABLE (IN1..IN4) at 320..323
# - Tweak substitutions in your main YAML as needed.

substitutions:
  dio_id: dio
  dio_address: "3"
  dio_prefix: "DIO"
  dio_update_interval: 1s
  dio_command_throttle: 0ms

modbus_controller:
  - id: ${dio_id}
    address: ${dio_address}
    modbus_id: modbus_bus
    command_throttle: ${dio_command_throttle}
    update_interval: ${dio_update_interval}

# ─────────────────────────────────────────────────────────────────────────────
# TELEMETRY (READ-ONLY): discrete_input registers
# ─────────────────────────────────────────────────────────────────────────────
binary_sensor:
  # DI1..DI4 (1..4)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} DI1"
    register_type: discrete_input
    address: 1
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} DI2"
    register_type: discrete_input
    address: 2
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} DI3"
    register_type: discrete_input
    address: 3
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} DI4"
    register_type: discrete_input
    address: 4

  # Relay logical state R1..R3 (60..62)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} RLY1 State"
    register_type: discrete_input
    address: 60
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} RLY2 State"
    register_type: discrete_input
    address: 61
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} RLY3 State"
    register_type: discrete_input
    address: 62

  # LED logical state LED1..LED3 (90..92)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} LED1 State"
    register_type: discrete_input
    address: 90
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} LED2 State"
    register_type: discrete_input
    address: 91
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} LED3 State"
    register_type: discrete_input
    address: 92

# ─────────────────────────────────────────────────────────────────────────────
# COMMANDS (WRITE-ONLY): pulse coils
# ─────────────────────────────────────────────────────────────────────────────
# Use `output.turn_on: <id>` to issue a pulse.
output:
  # Relay ON pulses (200..202)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_rly1_on
    address: 200
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_rly2_on
    address: 201
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_rly3_on
    address: 202

  # Relay OFF pulses (210..212)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_rly1_off
    address: 210
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_rly2_off
    address: 211
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_rly3_off
    address: 212

  # DI ENABLE pulses (300..303)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_di1_enable
    address: 300
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_di2_enable
    address: 301
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_di3_enable
    address: 302
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_di4_enable
    address: 303

  # DI DISABLE pulses (320..323)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_di1_disable
    address: 320
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_di2_disable
    address: 321
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_di3_disable
    address: 322
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_di4_disable
    address: 323

# ─────────────────────────────────────────────────────────────────────────────
# OPTIONAL UI BUTTONS — convenience triggers for pulses
# ─────────────────────────────────────────────────────────────────────────────
button:
  # Relay controls
  - platform: template
    name: "${dio_prefix} RLY1 ON"
    on_press:
      - output.turn_on: dio_rly1_on
  - platform: template
    name: "${dio_prefix} RLY1 OFF"
    on_press:
      - output.turn_on: dio_rly1_off
  - platform: template
    name: "${dio_prefix} RLY2 ON"
    on_press:
      - output.turn_on: dio_rly2_on
  - platform: template
    name: "${dio_prefix} RLY2 OFF"
    on_press:
      - output.turn_on: dio_rly2_off
  - platform: template
    name: "${dio_prefix} RLY3 ON"
    on_press:
      - output.turn_on: dio_rly3_on
  - platform: template
    name: "${dio_prefix} RLY3 OFF"
    on_press:
      - output.turn_on: dio_rly3_off

  # DI enable/disable
  - platform: template
    name: "${dio_prefix} DI1 Enable"
    on_press:
      - output.turn_on: dio_di1_enable
  - platform: template
    name: "${dio_prefix} DI1 Disable"
    on_press:
      - output.turn_on: dio_di1_disable
  - platform: template
    name: "${dio_prefix} DI2 Enable"
    on_press:
      - output.turn_on: dio_di2_enable
  - platform: template
    name: "${dio_prefix} DI2 Disable"
    on_press:
      - output.turn_on: dio_di2_disable
  - platform: template
    name: "${dio_prefix} DI3 Enable"
    on_press:
      - output.turn_on: dio_di3_enable
  - platform: template
    name: "${dio_prefix} DI3 Disable"
    on_press:
      - output.turn_on: dio_di3_disable
  - platform: template
    name: "${dio_prefix} DI4 Enable"
    on_press:
      - output.turn_on: dio_di4_enable
  - platform: template
    name: "${dio_prefix} DI4 Disable"
    on_press:
      - output.turn_on: dio_di4_disable
