# DIO-430-R1 — ESPHome Modbus map (package-friendly)
# Mirrors the firmware map in default_DIO_430_R1.ino
#
# Notes
# - Read-only states are exposed as `discrete_input` registers (FC=02)
#   • DI1..DI4 at 1..4
#   • Relay logical state R1..R3 at 60..62
#   • LED logical state LED1..LED3 at 90..92
# - Commands are *pulse* coils (FC=05/15): write TRUE momentarily; firmware auto-clears
#   • Relay ON  (R1..R3)  at 200..202
#   • Relay OFF (R1..R3)  at 210..212
#   • DI ENABLE (IN1..IN4) at 300..303
#   • DI DISABLE (IN1..IN4) at 320..323
# - Tweak substitutions in your main YAML as needed.

substitutions:
  dio_id: dio
  dio_address: "3"
  dio_prefix: "DIO"
  dio_update_interval: 1s
  dio_command_throttle: 0ms

modbus_controller:
  - id: ${dio_id}
    address: ${dio_address}
    modbus_id: modbus_bus
    command_throttle: ${dio_command_throttle}
    update_interval: ${dio_update_interval}

# ─────────────────────────────────────────────────────────────────────────────
# TELEMETRY (READ-ONLY): discrete_input registers
# ─────────────────────────────────────────────────────────────────────────────
binary_sensor:
  # DI1..DI4 (1..4)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} DI1"
    register_type: discrete_input
    address: 1
  # Relay logical state R1..R3 (60..62)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    name: "${dio_prefix} RLY1 State"
    register_type: discrete_input
    address: 60
# ─────────────────────────────────────────────────────────────────────────────
# COMMANDS (WRITE-ONLY): pulse coils
# ─────────────────────────────────────────────────────────────────────────────
# Use `output.turn_on: <id>` to issue a pulse.
output:
  # Relay ON pulses (200..202)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_rly1_on
    address: 200
  # Relay OFF pulses (210..212)
  - platform: modbus_controller
    modbus_controller_id: ${dio_id}
    register_type: coil
    id: dio_rly1_off
    address: 210