# ALM-173-R1 — ESPHome Modbus map (package-friendly, no flow mappings)
# You can override any of these in your main yaml's `substitutions:`.
substitutions:
  alm_id: alm
  alm_address: "3"
  alm_prefix: "ALM"
  alm_update_interval: 1s
  alm_command_throttle: 0ms

modbus_controller:
  - id: ${alm_id}
    address: ${alm_address}
    modbus_id: modbus_bus
    command_throttle: ${alm_command_throttle}
    update_interval: ${alm_update_interval}

# ─────────────────────────────────────────────────────────────────────────────
# TELEMETRY (READ-ONLY): discrete_input registers
# ─────────────────────────────────────────────────────────────────────────────
binary_sensor:
  # IN1..IN8
  - platform: modbus_controller
    modbus_controller_id: ${alm_id}
    name: "${alm_prefix} IN1"
    register_type: discrete_input
    address: 1
  
  # Effective relay states 60..62
  - platform: modbus_controller
    modbus_controller_id: ${alm_id}
    name: "${alm_prefix} Relay 1 State"
    register_type: discrete_input
    address: 60


# ─────────────────────────────────────────────────────────────────────────────
# COMMANDS (WRITE-ONLY): coils as outputs (ALM auto-clears pulses)
# ─────────────────────────────────────────────────────────────────────────────
output:
  # Acknowledge Alarms (500..503)
  - platform: modbus_controller
    modbus_controller_id: ${alm_id}
    register_type: coil
    id: alm_ack_all
    address: 500

  # Relay manual override pulses (ON 400..402 / OFF 420..422)
  - platform: modbus_controller
    modbus_controller_id: ${alm_id}
    register_type: coil
    id: alm_rly1_on
    address: 400

  - platform: modbus_controller
    modbus_controller_id: ${alm_id}
    register_type: coil
    id: alm_rly1_off
    address: 420




# ─────────────────────────────────────────────────────────────────────────────
# UI BUTTONS — call output.turn_on: <coil_id>
# ─────────────────────────────────────────────────────────────────────────────


  # Relay overrides
  - platform: template
    name: "${alm_prefix} Relay 1 ON"
    on_press:
      - output.turn_on: alm_rly1_on

  - platform: template
    name: "${alm_prefix} Relay 1 OFF"
    on_press:
      - output.turn_on: alm_rly1_off
