esphome:
  name: opentherm
  friendly_name: OpenTherm

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "rR4QfBRV9Qq7BWujlN4EgelqFdmk32CrvCOlhJRVvnA="

ota:
  - platform: esphome
    password: "8e324523d82a6077e7feea4eb6740837"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
#  manual_ip:
    # Set this to the IP of the ESP
#    static_ip: 192.168.1.22
    # Set this to the IP address of the router. Often ends with .1
#    gateway: 192.168.1.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
#    subnet: 255.255.255.0
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Opentherm Fallback Hotspot"
    password: "12345678"
  
captive_portal:

opentherm:
  in_pin: 21
  out_pin: 26

sensor:
  - platform: opentherm
    t_dhw:
      name: "DHW temperature (°C)"
    rel_mod_level: 
      name: "Relative modulation level (%)"
    ch_pressure: 
      name: "Water pressure in CH circuit (bar)"
    dhw_flow_rate: 
      name: "Water flow rate in DHW circuit (l/min)"
    t_boiler: 
      name: "Boiler water temperature (°C)"
    t_exhaust: 
      name: "Boiler exhaust temperature (°C)"
    t_dhw_set_ub: 
      name: "Upper bound for adjustment of DHW setpoint (°C)"
    t_dhw_set_lb: 
      name: "Lower bound for adjustment of DHW setpoint (°C)"
    max_t_set_ub: 
      name: "Upper bound for adjustment of max CH setpoint (°C)"
    max_t_set_lb: 
      name: "Lower bound for adjustment of max CH setpoint (°C)"
    t_dhw_set: 
      name: "Domestic hot water temperature setpoint (°C)"
    max_t_set: 
      name: "Maximum allowable CH water setpoint (°C)"

binary_sensor:
  - platform: opentherm
    ch_active:
      name: "Boiler Central Heating active"
    dhw_active:
      name: "Boiler Domestic Hot Water active"
    flame_on:
      name: "Boiler Flame on"
    fault_indication:
      name: "Boiler Fault indication"
      entity_category: diagnostic
    diagnostic_indication:
      name: "Boiler Diagnostic event"
      entity_category: diagnostic
  - platform: gpio
    name: "Button #1"
    pin: GPIO35

one_wire:
  - platform: gpio
    pin: GPIO04
    id: hub_1
  - platform: gpio
    pin: GPIO02
    id: hub_2

switch:
  - platform: gpio
    pin: GPIO25
    name: "LED2"
  - platform: gpio
    pin: GPIO32
    name: "RELAY"



#sensor:
#  - platform: dallas_temp
#    one_wire_id: hub_1
#    address: 0x6f7c86e908646128
#    name: "1-WIRE Dallas temperature BUS1"
#    update_interval: 60s
#  - platform: dallas_temp
#    one_wire_id: hub_2
#    address: 0xbc3c01d075cb5128
#    name: "1-WIRE Dallas temperature BUS2"
#    update_interval: 60s

status_led:
  pin:
     number: GPIO33
     inverted: true