modbus_controller:
  - id: ${aio_id}
    address: ${aio_address}
    modbus_id: modbus_bus
    update_interval: 5s        # was 1s
    command_throttle: 2s     # add a small gap between frames

# ------------- Discrete Inputs (LEDs + RTD faults only) -------------
binary_sensor:
  # MAX31865 fault flags 360..361
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} RTD1 Fault"
    address: 360
    register_type: discrete_input

# ------------- Numbers (Holding Registers: DAC raw only) -------------
number:
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} DAC1 Raw"
    address: 211
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 4095
    step: 1
    mode: slider
    unit_of_measurement: "code"
# ---------------- Sensors (Input Registers: AI/RTD/DAC mV) ----------------
sensor:
  # ADS1115 — field mV (U_WORD) @ 120..123
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch0_mv
    name: "${aio_prefix} CH0 mV"
    address: 120
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

