modbus_controller:
  - id: ${aio_id}
    address: ${aio_address}
    modbus_id: modbus_bus
    update_interval: 2s

binary_sensor:
  # ---- Buttons (Discrete Inputs) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button 1"
    address: 1
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button 2"
    address: 2
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button 3"
    address: 3
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button 4"
    address: 4
    register_type: discrete_input

  # ---- LEDs (Discrete Inputs) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED 1"
    address: 20
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED 2"
    address: 21
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED 3"
    address: 22
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED 4"
    address: 23
    register_type: discrete_input


# ================= WRITEABLE Holding Registers =================
number:
  # ---- DAC outputs ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AO0 Raw"
    address: 200
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 4095
    step: 1
    mode: slider

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AO1 Raw"
    address: 201
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 4095
    step: 1
    mode: slider

  # ---- PID Setpoints (raw) 300..303 (S_WORD) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 SP Raw"
    address: 300
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 SP Raw"
    address: 301
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 SP Raw"
    address: 302
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 SP Raw"
    address: 303
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  # ---- PID Enable 310..313 (0/1) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 Enable"
    address: 310
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 Enable"
    address: 311
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 Enable"
    address: 312
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 Enable"
    address: 313
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 1
    step: 1
    mode: box

  # ---- PID gains RAW (x100): Kp 350..353, Ki 360..363, Kd 370..373 ----
  # Write raw integers; use sensors below to show scaled float.
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 Kp x100"
    address: 350
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 Kp x100"
    address: 351
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 Kp x100"
    address: 352
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 Kp x100"
    address: 353
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 Ki x100"
    address: 360
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 Ki x100"
    address: 361
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 Ki x100"
    address: 362
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 Ki x100"
    address: 363
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 Kd x100"
    address: 370
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 Kd x100"
    address: 371
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 Kd x100"
    address: 372
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 Kd x100"
    address: 373
    register_type: holding
    value_type: S_WORD
    step: 1
    mode: box


# ================= READABLE Holding Registers =================
sensor:
  # ---- RTD temperatures (°C*10 as S_WORD) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} RTD1 Temperature"
    address: 120
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} RTD2 Temperature"
    address: 121
    register_type: holding
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  # ---- AI field voltage in mV (U_WORD) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AI0 mV"
    address: 140
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AI1 mV"
    address: 141
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AI2 mV"
    address: 142
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AI3 mV"
    address: 143
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  # ---- PID OUT raw (0..4095) 380..383 ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 OUT Raw"
    address: 380
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "code"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 OUT Raw"
    address: 381
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "code"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 OUT Raw"
    address: 382
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "code"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 OUT Raw"
    address: 383
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "code"
    accuracy_decimals: 0

  # ---- PID gains scaled (read-only display, from same regs) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 Kp"
    address: 350
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 Ki"
    address: 360
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID1 Kd"
    address: 370
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 Kp"
    address: 351
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 Ki"
    address: 361
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID2 Kd"
    address: 371
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 Kp"
    address: 352
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 Ki"
    address: 362
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID3 Kd"
    address: 372
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 Kp"
    address: 353
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 Ki"
    address: 363
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} PID4 Kd"
    address: 373
    register_type: holding
    value_type: S_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
