modbus_controller:
  - id: ${aio_id}
    address: ${aio_address}
    modbus_id: modbus_bus
    update_interval: 1s
    command_throttle: 10ms

binary_sensor:
  # ---- Buttons ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button 1"
    address: 1
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button 2"
    address: 2
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button 3"
    address: 3
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button 4"
    address: 4
    register_type: discrete_input

  # ---- LEDs (read-only state from firmware) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED 1"
    address: 20
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED 2"
    address: 21
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED 3"
    address: 22
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED 4"
    address: 23
    register_type: discrete_input


# ================= DACs (Holding Registers) =================
# FW map:
#   HREG_DAC_BASE = 200
#   200 = AO0 raw (DAC0), 201 = AO1 raw (DAC1)
number:
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AO0 Raw"
    address: 200
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "code"
    min_value: 0
    max_value: 4095
    step: 1
    mode: slider

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AO1 Raw"
    address: 201
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "code"
    min_value: 0
    max_value: 4095
    step: 1
    mode: slider


# ================= Sensors (AI raw, AI mV, RTD temps) =================
# FW map:
#   IREG_AI_BASE    = 100  → 100..103 = ADS1115 raw counts (int16)
#   IREG_TEMP_BASE  = 120  → 120..121 = RTD temps *10 °C (signed)
#   IREG_AI_MV_BASE = 140  → 140..143 = AI field voltage in mV (0..10000)
sensor:
  # ---- AI raw counts ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AI0 Raw"
    address: 100
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "cnt"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AI1 Raw"
    address: 101
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "cnt"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AI2 Raw"
    address: 102
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "cnt"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} AI3 Raw"
    address: 103
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "cnt"
    accuracy_decimals: 0
  # ---- RTD temperatures (PT100 via MAX31865) ----
  # firmware reports °C * 10 as signed int16
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} RTD1 Temperature"
    address: 120
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} RTD2 Temperature"
    address: 121
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    filters:
      - multiply: 0.1
  # ---- AI field voltage in mV (0–10000 mV) ----
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch0_mv
    name: "${aio_prefix} AI0 mV"
    address: 140
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch1_mv
    name: "${aio_prefix} AI1 mV"
    address: 141
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch2_mv
    name: "${aio_prefix} AI2 mV"
    address: 142
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch3_mv
    name: "${aio_prefix} AI3 mV"
    address: 143
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

