modbus_controller:
  - id: ${aio_id}
    address: ${aio_address}
    modbus_id: modbus_bus
    update_interval: 1s
    command_throttle: 0ms

# ------------- Discrete Inputs (LEDs, Buttons, RTD faults) -------------
binary_sensor:
  # LED states 300..303
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED1"
    address: 300
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED2"
    address: 301
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED3"
    address: 302
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} LED4"
    address: 303
    register_type: discrete_input

  # Button states 320..323
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button1"
    address: 320
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button2"
    address: 321
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button3"
    address: 322
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} Button4"
    address: 323
    register_type: discrete_input

  # MAX31865 fault flags 360..361
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} RTD1 Fault"
    address: 360
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} RTD2 Fault"
    address: 361
    register_type: discrete_input


# ------------- Numbers (Holding Registers) -------------
number:
  # NEW: DAC raw codes (0..4095)
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} DAC0 Raw"
    address: 210
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 4095
    step: 1
    mode: slider
    unit_of_measurement: "code"

  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    name: "${aio_prefix} DAC1 Raw"
    address: 211
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 4095
    step: 1
    mode: slider
    unit_of_measurement: "code"

# ---------------- Sensors (Input Registers) ----------------
sensor:
  # ADS1115 — field mV (U_WORD) @ 120..123
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch0_mv
    name: "${aio_prefix} CH0 mV"
    address: 120
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch1_mv
    name: "${aio_prefix} CH1 mV"
    address: 121
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch2_mv
    name: "${aio_prefix} CH2 mV"
    address: 122
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch3_mv
    name: "${aio_prefix} CH3 mV"
    address: 123
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0

  # ADS1115 — raw counts (S_WORD) @ 100..103
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch0_raw
    name: "${aio_prefix} CH0 raw"
    address: 100
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "cnt"
    accuracy_decimals: 0
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch1_raw
    name: "${aio_prefix} CH1 raw"
    address: 101
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "cnt"
    accuracy_decimals: 0
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch2_raw
    name: "${aio_prefix} CH2 raw"
    address: 102
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "cnt"
    accuracy_decimals: 0
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ch3_raw
    name: "${aio_prefix} CH3 raw"
    address: 103
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "cnt"
    accuracy_decimals: 0

  # MAX31865 — °C x100 (S_WORD) @ 140..141
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: rtd1_cx100
    name: "${aio_prefix} RTD1 Temperature"
    address: 140
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: rtd2_cx100
    name: "${aio_prefix} RTD2 Temperature"
    address: 141
    register_type: read
    value_type: S_WORD
    unit_of_measurement: "°C"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # MAX31865 — Ohm x100 (U_WORD) @ 150..151
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: rtd1_ohmx100
    name: "${aio_prefix} RTD1 Resistance"
    address: 150
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "Ω"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: rtd2_ohmx100
    name: "${aio_prefix} RTD2 Resistance"
    address: 151
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "Ω"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  # DAC field outputs (mV) @ 180..181
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ao0_mv
    name: "${aio_prefix} AO0 mV"
    address: 180
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0
  - platform: modbus_controller
    modbus_controller_id: ${aio_id}
    id: ao1_mv
    name: "${aio_prefix} AO1 mV"
    address: 181
    register_type: read
    value_type: U_WORD
    unit_of_measurement: "mV"
    accuracy_decimals: 0
