##
## WLD-521-R1 — ESPHome Modbus package (MiniPLC/MicroPLC ↔ WLD)
##

substitutions:
  wld_id: wld_1
  wld_prefix: "WLD#1"
  wld_address: "3"     # firmware default Modbus ID

# If UART/MODBUS aren’t defined globally, uncomment & set pins:
# uart:
#   id: rs485_uart
#   tx_pin: GPIO4
#   rx_pin: GPIO5
#   baud_rate: 19200
#   parity: NONE
#   stop_bits: 1
# modbus:
#   id: modbus_bus
#   uart_id: rs485_uart

modbus_controller:
  - id: ${wld_id}
    address: ${wld_address}
    modbus_id: modbus_bus
    update_interval: 1s
    command_throttle: 0ms

# ===================== Discrete Inputs (FC02) =====================
binary_sensor:
  # DI states (1..5)
  - platform: modbus_controller
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} DI1"
    address: 1
    register_type: discrete_input


  # Relay feedback (60..61)
  - platform: modbus_controller
    id: ${wld_id}_r1_state
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} R1 state"
    address: 60
    register_type: discrete_input

# ===================== Command Coils (FC05/FC01) =====================
# Relay coils are maintained (not pulses). ESPHome can set ON/OFF directly.
switch:
  - platform: modbus_controller
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} Relay 1"
    address: 200
    register_type: coil

  - platform: modbus_controller
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} Relay 2"
    address: 201
    register_type: coil

  # DI enable coils (maintained - ESPHome can enable/disable inputs directly)
  - platform: modbus_controller
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} DI1 Enable"
    address: 220
    register_type: coil

  - platform: modbus_controller
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} DI2 Enable"
    address: 221
    register_type: coil

  - platform: modbus_controller
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} DI3 Enable"
    address: 222
    register_type: coil

  - platform: modbus_controller
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} DI4 Enable"
    address: 223
    register_type: coil

  - platform: modbus_controller
    modbus_controller_id: ${wld_id}
    name: "${wld_prefix} DI5 Enable"
    address: 224
    register_type: coil
