##
## WLD-521-R1 — ESPHome Modbus package (MiniPLC/MicroPLC ↔ WLD)
##

substitutions:
  wld_id: wld_1
  wld_prefix: "WLD#1"
  wld_address: "3"     # firmware default Modbus ID

# If UART/MODBUS aren’t defined globally, uncomment & set pins:
# uart:
#   id: rs485_uart
#   tx_pin: GPIO4         # set to your RS-485 TX
#   rx_pin: GPIO5         # set to your RS-485 RX
#   baud_rate: 19200
#   parity: NONE
#   stop_bits: 1
# modbus:
#   id: modbus_bus
#   uart_id: rs485_uart

modbus_controller:
  - id: ${wld_id}
    address: ${wld_address}
    modbus_id: modbus_bus
    update_interval: 1s
    command_throttle: 0ms

##
## WLD-521-R1 — ESPHome Modbus external package (MiniPLC/MicroPLC ↔ WLD)
## Cleaned for ESPHome YAML (no Jinja, valid automations)
##

# ===================== Discrete Inputs (FC02) =====================
# DI states: 1..5 | Relay feedback: 60..61 | LED mirrors: 90..93 | BTN mirrors: 100..103

#########################################################
# READ-ONLY MIRROR STATES (Discrete Inputs / LEDs / BTN)
#########################################################
binary_sensor:
  # DI1..DI5 → Ists 1..5
  - platform: modbus_controller
    name: "${wld_prefix} DI1"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 1
  - platform: modbus_controller
    name: "${wld_prefix} DI2"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 2
  - platform: modbus_controller
    name: "${wld_prefix} DI3"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 3
  - platform: modbus_controller
    name: "${wld_prefix} DI4"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 4
  - platform: modbus_controller
    name: "${wld_prefix} DI5"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 5

  # Relay mirror (Ists 60..61)
  - platform: modbus_controller
    name: "${wld_prefix} Relay R1 (state)"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 60
  - platform: modbus_controller
    name: "${wld_prefix} Relay R2 (state)"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 61

  # LED mirrors (Ists 90..93)
  - platform: modbus_controller
    name: "${wld_prefix} LED1"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 90
  - platform: modbus_controller
    name: "${wld_prefix} LED2"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 91
  - platform: modbus_controller
    name: "${wld_prefix} LED3"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 92
  - platform: modbus_controller
    name: "${wld_prefix} LED4"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 93

  # Button mirrors (Ists 100..103)
  - platform: modbus_controller
    name: "${wld_prefix} BTN1"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 100
  - platform: modbus_controller
    name: "${wld_prefix} BTN2"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 101
  - platform: modbus_controller
    name: "${wld_prefix} BTN3"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 102
  - platform: modbus_controller
    name: "${wld_prefix} BTN4"
    modbus_controller_id: wld
    register_type: discrete_input
    address: 103

##############################################
# HOLDING REGISTERS: TIME / DAY
##############################################
sensor:
  - platform: modbus_controller
    name: "${wld_prefix} Minutes Since Midnight"
    modbus_controller_id: wld
    register_type: holding
    address: 1100
    value_type: U_WORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} Day Index"
    modbus_controller_id: wld
    register_type: holding
    address: 1101
    value_type: U_WORD
    accuracy_decimals: 0

##############################################
# FLOW per DI (1120/1140 blocks) 32-bit
##############################################
  # Rate L/min ×1000 (U32)
  - platform: modbus_controller
    name: "${wld_prefix} DI1 Flow Rate L/min"
    modbus_controller_id: wld
    register_type: holding
    address: 1120
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI2 Flow Rate L/min"
    modbus_controller_id: wld
    register_type: holding
    address: 1122
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI3 Flow Rate L/min"
    modbus_controller_id: wld
    register_type: holding
    address: 1124
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI4 Flow Rate L/min"
    modbus_controller_id: wld
    register_type: holding
    address: 1126
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI5 Flow Rate L/min"
    modbus_controller_id: wld
    register_type: holding
    address: 1128
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # Accumulator Liters ×1000 (U32)
  - platform: modbus_controller
    name: "${wld_prefix} DI1 Total Liters"
    modbus_controller_id: wld
    register_type: holding
    address: 1140
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI2 Total Liters"
    modbus_controller_id: wld
    register_type: holding
    address: 1142
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI3 Total Liters"
    modbus_controller_id: wld
    register_type: holding
    address: 1144
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI4 Total Liters"
    modbus_controller_id: wld
    register_type: holding
    address: 1146
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI5 Total Liters"
    modbus_controller_id: wld
    register_type: holding
    address: 1148
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

##############################################
# HEAT per DI (power W, energy Wh×1000, ΔT °C×1000)
##############################################
  # Power (S32, Watts)
  - platform: modbus_controller
    name: "${wld_prefix} DI1 Heat Power W"
    modbus_controller_id: wld
    register_type: holding
    address: 1200
    value_type: S_DWORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} DI2 Heat Power W"
    modbus_controller_id: wld
    register_type: holding
    address: 1202
    value_type: S_DWORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} DI3 Heat Power W"
    modbus_controller_id: wld
    register_type: holding
    address: 1204
    value_type: S_DWORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} DI4 Heat Power W"
    modbus_controller_id: wld
    register_type: holding
    address: 1206
    value_type: S_DWORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} DI5 Heat Power W"
    modbus_controller_id: wld
    register_type: holding
    address: 1208
    value_type: S_DWORD
    accuracy_decimals: 0

  # Energy (U32, Wh ×1000)
  - platform: modbus_controller
    name: "${wld_prefix} DI1 Heat Energy kWh"
    modbus_controller_id: wld
    register_type: holding
    address: 1220
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI2 Heat Energy kWh"
    modbus_controller_id: wld
    register_type: holding
    address: 1222
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI3 Heat Energy kWh"
    modbus_controller_id: wld
    register_type: holding
    address: 1224
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI4 Heat Energy kWh"
    modbus_controller_id: wld
    register_type: holding
    address: 1226
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI5 Heat Energy kWh"
    modbus_controller_id: wld
    register_type: holding
    address: 1228
    value_type: U_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  # ΔT (S32, °C ×1000)
  - platform: modbus_controller
    name: "${wld_prefix} DI1 ΔT °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1240
    value_type: S_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI2 ΔT °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1242
    value_type: S_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI3 ΔT °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1244
    value_type: S_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI4 ΔT °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1246
    value_type: S_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001
  - platform: modbus_controller
    name: "${wld_prefix} DI5 ΔT °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1248
    value_type: S_DWORD
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

##############################################
# IRRIGATION (zones Z1..Z2)
##############################################
  # State (enum, U16)
  - platform: modbus_controller
    name: "${wld_prefix} Irrigation Z1 State"
    modbus_controller_id: wld
    register_type: holding
    address: 1300
    value_type: U_WORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} Irrigation Z2 State"
    modbus_controller_id: wld
    register_type: holding
    address: 1301
    value_type: U_WORD
    accuracy_decimals: 0

  # Liters ×1000 (U32)
  - platform: modbus_controller
    name: "${wld_prefix} Irrigation Z1 Liters"
    modbus_controller_id: wld
    register_type: holding
    address: 1310
    value_type: U_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} Irrigation Z2 Liters"
    modbus_controller_id: wld
    register_type: holding
    address: 1312
    value_type: U_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]

  # Elapsed seconds (U32)
  - platform: modbus_controller
    name: "${wld_prefix} Irrigation Z1 Elapsed s"
    modbus_controller_id: wld
    register_type: holding
    address: 1320
    value_type: U_DWORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} Irrigation Z2 Elapsed s"
    modbus_controller_id: wld
    register_type: holding
    address: 1322
    value_type: U_DWORD
    accuracy_decimals: 0

  # Rate L/min ×1000 (U32)
  - platform: modbus_controller
    name: "${wld_prefix} Irrigation Z1 Rate L/min"
    modbus_controller_id: wld
    register_type: holding
    address: 1330
    value_type: U_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} Irrigation Z2 Rate L/min"
    modbus_controller_id: wld
    register_type: holding
    address: 1332
    value_type: U_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]

  # Window flags & Sensor OK flags (U16 each)
  - platform: modbus_controller
    name: "${wld_prefix} Z1 Window Open"
    modbus_controller_id: wld
    register_type: holding
    address: 1340
    value_type: U_WORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} Z2 Window Open"
    modbus_controller_id: wld
    register_type: holding
    address: 1341
    value_type: U_WORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} Z1 Sensors OK"
    modbus_controller_id: wld
    register_type: holding
    address: 1342
    value_type: U_WORD
    accuracy_decimals: 0
  - platform: modbus_controller
    name: "${wld_prefix} Z2 Sensors OK"
    modbus_controller_id: wld
    register_type: holding
    address: 1343
    value_type: U_WORD
    accuracy_decimals: 0

##############################################
# 1-WIRE TEMPERATURES (k = 1..10) S32 °C×1000
##############################################
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 1 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1500
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 2 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1502
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 3 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1504
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 4 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1506
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 5 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1508
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 6 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1510
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 7 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1512
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 8 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1514
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 9 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1516
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]
  - platform: modbus_controller
    name: "${wld_prefix} 1W Temp 10 °C"
    modbus_controller_id: wld
    register_type: holding
    address: 1518
    value_type: S_DWORD
    accuracy_decimals: 3
    filters: [ { multiply: 0.001 } ]

#########################################################
# COMMAND COILS (momentary pulses) as BUTTONS
#########################################################
button:
  # Relay control (separate ON/OFF pulses)
  - platform: template
    name: "${wld_prefix} R1 ON"
    on_press:
      - modbus_controller.write_coil:
          id: wld
          address: 200
          value: true
  - platform: template
    name: "${wld_prefix} R1 OFF"
    on_press:
      - modbus_controller.write_coil:
          id: wld
          address: 210
          value: true
  - platform: template
    name: "${wld_prefix} R2 ON"
    on_press:
      - modbus_controller.write_coil:
          id: wld
          address: 201
          value: true
  - platform: template
    name: "${wld_prefix} R2 OFF"
    on_press:
      - modbus_controller.write_coil:
          id: wld
          address: 211
          value: true

  # DI enable / disable / counter reset (1..5)
  - platform: template
    name: "${wld_prefix} DI1 Enable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 300, value: true } }
  - platform: template
    name: "${wld_prefix} DI2 Enable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 301, value: true } }
  - platform: template
    name: "${wld_prefix} DI3 Enable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 302, value: true } }
  - platform: template
    name: "${wld_prefix} DI4 Enable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 303, value: true } }
  - platform: template
    name: "${wld_prefix} DI5 Enable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 304, value: true } }

  - platform: template
    name: "${wld_prefix} DI1 Disable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 320, value: true } }
  - platform: template
    name: "${wld_prefix} DI2 Disable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 321, value: true } }
  - platform: template
    name: "${wld_prefix} DI3 Disable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 322, value: true } }
  - platform: template
    name: "${wld_prefix} DI4 Disable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 323, value: true } }
  - platform: template
    name: "${wld_prefix} DI5 Disable"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 324, value: true } }

  - platform: template
    name: "${wld_prefix} DI1 Counter Reset"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 340, value: true } }
  - platform: template
    name: "${wld_prefix} DI2 Counter Reset"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 341, value: true } }
  - platform: template
    name: "${wld_prefix} DI3 Counter Reset"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 342, value: true } }
  - platform: template
    name: "${wld_prefix} DI4 Counter Reset"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 343, value: true } }
  - platform: template
    name: "${wld_prefix} DI5 Counter Reset"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 344, value: true } }

  # Midnight pulse
  - platform: template
    name: "${wld_prefix} Midnight Pulse"
    on_press:
      - modbus_controller.write_coil:
          id: wld
          address: 360
          value: true

  # Irrigation Z1..Z2 start/stop/reset
  - platform: template
    name: "${wld_prefix} Irrigation Z1 START"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 370, value: true } }
  - platform: template
    name: "${wld_prefix} Irrigation Z2 START"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 371, value: true } }
  - platform: template
    name: "${wld_prefix} Irrigation Z1 STOP"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 380, value: true } }
  - platform: template
    name: "${wld_prefix} Irrigation Z2 STOP"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 381, value: true } }
  - platform: template
    name: "${wld_prefix} Irrigation Z1 RESET"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 390, value: true } }
  - platform: template
    name: "${wld_prefix} Irrigation Z2 RESET"
    on_press: { then: - modbus_controller.write_coil: { id: wld, address: 391, value: true } }