modbus_controller:
  - id: ${rgb_id}
    address: ${rgb_address}
    modbus_id: modbus_bus
    update_interval: 1s
    command_throttle: 0ms

# ===================== Discrete Inputs (FC02) =====================
binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI1"
    address: 1
    register_type: discrete_input

output:
  - platform: modbus_controller
    id: rgb621_out_r
    modbus_controller_id: ${rgb_id}
    address: 400
    register_type: holding
    value_type: U_WORD
    multiply: 255.0

  - platform: modbus_controller
    id: rgb621_out_g
    modbus_controller_id: ${rgb_id}
    address: 401
    register_type: holding
    value_type: U_WORD
    multiply: 255.0

  - platform: modbus_controller
    id: rgb621_out_b
    modbus_controller_id: ${rgb_id}
    address: 402
    register_type: holding
    value_type: U_WORD
    multiply: 255.0