modbus_controller:
  - id: ${rgb_id}
    address: ${rgb_address}
    modbus_id: modbus_bus
    update_interval: 1s
    command_throttle: 0ms

# ===================== Discrete Inputs (FC02) =====================
binary_sensor:
  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI1"
    address: 1
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI2"
    address: 2
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} Relay1 State"
    address: 60
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} LED1"
    address: 90
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} LED2"
    address: 91
    register_type: discrete_input

# ===================== Coils (FC01/05) — pulses =====================
switch:
  - platform: modbus_controller
    id: ${rgb_id}_rly1_on
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} Relay1 ON (Pulse)"
    address: 200
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_rly1_on

  - platform: modbus_controller
    id: ${rgb_id}_rly1_off
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} Relay1 OFF (Pulse)"
    address: 210
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_rly1_off

  - platform: modbus_controller
    id: ${rgb_id}_di1_enable
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI1 Enable (Pulse)"
    address: 300
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_di1_enable

  - platform: modbus_controller
    id: ${rgb_id}_di2_enable
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI2 Enable (Pulse)"
    address: 301
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_di2_enable

  - platform: modbus_controller
    id: ${rgb_id}_di1_disable
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI1 Disable (Pulse)"
    address: 320
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_di1_disable

  - platform: modbus_controller
    id: ${rgb_id}_di2_disable
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI2 Disable (Pulse)"
    address: 321
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_di2_disable

# ===================== Holding (FC03/06/16) =====================
# 5 sliders that write HR 400..404 (0..255). Also HR 480/481.
number:
  - platform: modbus_controller
    id: ${rgb_id}_r_level
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} R Level"
    address: 400
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    id: ${rgb_id}_g_level
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} G Level"
    address: 401
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    id: ${rgb_id}_b_level
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} B Level"
    address: 402
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    id: ${rgb_id}_ww_level
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} WW Level"
    address: 403
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    id: ${rgb_id}_cw_level
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} CW Level"
    address: 404
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    id: ${rgb_id}_mb_addr
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} MB Address"
    address: 480
    register_type: holding
    value_type: U_WORD
    min_value: 1
    max_value: 247
    step: 1

  - platform: modbus_controller
    id: ${rgb_id}_mb_baud
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} MB Baud"
    address: 481
    register_type: holding
    value_type: U_WORD
    min_value: 9600
    max_value: 115200
    step: 1

# ===================== All Off (uses number.set only) =====================
button:
  - platform: template
    name: "${rgb_prefix} All Channels OFF"
    on_press:
      - number.set: { id: ${rgb_id}_r_level,  value: 0 }
      - number.set: { id: ${rgb_id}_g_level,  value: 0 }
      - number.set: { id: ${rgb_id}_b_level,  value: 0 }
      - number.set: { id: ${rgb_id}_ww_level, value: 0 }
      - number.set: { id: ${rgb_id}_cw_level, value: 0 }

# ===================== One Light via template outputs =====================
# These outputs mirror the light's channels into the five Modbus numbers.
output:
  - platform: template
    id: ${rgb_id}_out_r
    type: float
    write_action:
      - number.set:
          id: ${rgb_id}_r_level
          value: !lambda 'return roundf(state * 255.0f);'

  - platform: template
    id: ${rgb_id}_out_g
    type: float
    write_action:
      - number.set:
          id: ${rgb_id}_g_level
          value: !lambda 'return roundf(state * 255.0f);'

  - platform: template
    id: ${rgb_id}_out_b
    type: float
    write_action:
      - number.set:
          id: ${rgb_id}_b_level
          value: !lambda 'return roundf(state * 255.0f);'

  - platform: template
    id: ${rgb_id}_out_ww
    type: float
    write_action:
      - number.set:
          id: ${rgb_id}_ww_level
          value: !lambda 'return roundf(state * 255.0f);'

  - platform: template
    id: ${rgb_id}_out_cw
    type: float
    write_action:
      - number.set:
          id: ${rgb_id}_cw_level
          value: !lambda 'return roundf(state * 255.0f);'

light:
  - platform: rgbww
    id: ${rgb_id}_light
    name: "${rgb_prefix} Light"
    red: ${rgb_id}_out_r
    green: ${rgb_id}_out_g
    blue: ${rgb_id}_out_b
    warm_white: ${rgb_id}_out_ww
    cold_white: ${rgb_id}_out_cw
    default_transition_length: 150ms
    restore_mode: ALWAYS_OFF
