modbus_controller:
  - id: ${rgb_id}
    address: ${rgb_address}
    modbus_id: modbus_bus
    update_interval: 2s        # was 1s
    command_throttle: 10ms     # add a small gap between frames
    setup_priority: -10.0      # start after UART/modbus is ready

# ===================== Discrete Inputs (FC02) =====================
binary_sensor:
  # --- Digital Inputs DI1..DI2 ---
  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI1"
    address: 1
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI2"
    address: 2
    register_type: discrete_input

  # --- Relay1 logical state (after cfg/invert) ---
  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} Relay1 State"
    address: 60
    register_type: discrete_input

  # --- LED logical states ---
  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} LED1"
    address: 90
    register_type: discrete_input

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} LED2"
    address: 91
    register_type: discrete_input

# ===================== Coils (FC01/05) — momentary pulses =====================
# Relay1 ON: 200 | Relay1 OFF: 210
# DI1..2 ENABLE: 300..301 | DI1..2 DISABLE: 320..321
switch:
  # --- Relay ON/OFF pulses (auto-off in 200ms) ---
  - platform: modbus_controller
    id: ${rgb_id}_rly1_on
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} Relay1 ON (Pulse)"
    address: 200
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_rly1_on

  - platform: modbus_controller
    id: ${rgb_id}_rly1_off
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} Relay1 OFF (Pulse)"
    address: 210
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_rly1_off

  # --- DI enable/disable pulses ---
  - platform: modbus_controller
    id: ${rgb_id}_di1_enable
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI1 Enable (Pulse)"
    address: 300
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_di1_enable

  - platform: modbus_controller
    id: ${rgb_id}_di2_enable
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI2 Enable (Pulse)"
    address: 301
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_di2_enable

  - platform: modbus_controller
    id: ${rgb_id}_di1_disable
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI1 Disable (Pulse)"
    address: 320
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_di1_disable

  - platform: modbus_controller
    id: ${rgb_id}_di2_disable
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} DI2 Disable (Pulse)"
    address: 321
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${rgb_id}_di2_disable

# ===================== Numbers (FC03/06/16 Holding) =====================
# PWM level sliders: 0..255 for R,G,B,WW,CW at 400..404
number:
  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} R Level"
    address: 400
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} G Level"
    address: 401
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} B Level"
    address: 402
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} WW Level"
    address: 403
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} CW Level"
    address: 404
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  # --- Optional: Modbus address / baud (take effect immediately on device) ---
  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} MB Address"
    address: 480
    register_type: holding
    value_type: U_WORD
    min_value: 1
    max_value: 247
    step: 1

  - platform: modbus_controller
    modbus_controller_id: ${rgb_id}
    name: "${rgb_prefix} MB Baud"
    address: 481
    register_type: holding
    value_type: U_WORD
    min_value: 9600
    max_value: 115200
    step: 1
    # TIP: use standard values (9600/19200/38400/57600/115200)

# ===================== Convenience: One-shot "All Off" button =====================
# Uses lambda (works on all ESPHome versions)
button:
  - platform: template
    name: "${rgb_prefix} All Channels OFF"
    on_press:
      - lambda: |-
          id(${rgb_id}).write_single_register(400, 0);
          id(${rgb_id}).write_single_register(401, 0);
          id(${rgb_id}).write_single_register(402, 0);
          id(${rgb_id}).write_single_register(403, 0);
          id(${rgb_id}).write_single_register(404, 0);

# ===================== One Light entity via template outputs =====================
# Writes holding registers 400..404 whenever the light changes.
output:
  - platform: template
    id: ${rgb_id}_out_r
    type: float
    write_action:
      - lambda: |-
          uint16_t v = (uint16_t) roundf(state * 255.0f);
          id(${rgb_id}).write_single_register(400, v);

  - platform: template
    id: ${rgb_id}_out_g
    type: float
    write_action:
      - lambda: |-
          uint16_t v = (uint16_t) roundf(state * 255.0f);
          id(${rgb_id}).write_single_register(401, v);

  - platform: template
    id: ${rgb_id}_out_b
    type: float
    write_action:
      - lambda: |-
          uint16_t v = (uint16_t) roundf(state * 255.0f);
          id(${rgb_id}).write_single_register(402, v);

  - platform: template
    id: ${rgb_id}_out_ww
    type: float
    write_action:
      - lambda: |-
          uint16_t v = (uint16_t) roundf(state * 255.0f);
          id(${rgb_id}).write_single_register(403, v);

  - platform: template
    id: ${rgb_id}_out_cw
    type: float
    write_action:
      - lambda: |-
          uint16_t v = (uint16_t) roundf(state * 255.0f);
          id(${rgb_id}).write_single_register(404, v);

light:
  - platform: rgbww
    id: ${rgb_id}_light
    name: "${rgb_prefix} Light"
    red: ${rgb_id}_out_r
    green: ${rgb_id}_out_g
    blue: ${rgb_id}_out_b
    warm_white: ${rgb_id}_out_ww
    cold_white: ${rgb_id}_out_cw
    default_transition_length: 150ms
    restore_mode: ALWAYS_OFF   # optional; remove if you prefer remembering last state
