modbus_controller:
  - id: ${dim_id}
    address: ${dim_address}       # DIM-420-R1 slave ID
    modbus_id: modbus_bus
    update_interval: 1s
    command_throttle: 0ms

# ===================== Discrete Inputs (FC02) =====================
# DI states: 1..4 | CH on mirrors: 50..51 | LED states: 90..93 | ZC OK: 120..121
binary_sensor:
  # --- Digital Inputs DI1..DI4 ---
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} DI1"
    address: 1
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} DI2"
    address: 2
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} DI3"
    address: 3
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} DI4"
    address: 4
    register_type: discrete_input

  # --- Channel ON mirrors (enabled && level>0) ---
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH1 On"
    address: 50
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH2 On"
    address: 51
    register_type: discrete_input

   # --- Zero-cross health ---
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} ZC1 OK"
    address: 120
    register_type: discrete_input
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} ZC2 OK"
    address: 121
    register_type: discrete_input

# ===================== Coils (FC01/05) — momentary pulses =====================
# CH1/2 ON: 200/201 | CH1/2 OFF: 210/211
# DI1..4 ENABLE: 300..303 | DI1..4 DISABLE: 320..323
switch:
  # --- Channel ON/OFF pulses ---
  - platform: modbus_controller
    id: ${dim_id}_ch1_on
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH1 ON (Preset)"
    address: 200
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${dim_id}_ch1_on

  - platform: modbus_controller
    id: ${dim_id}_ch2_on
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH2 ON (Preset)"
    address: 201
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${dim_id}_ch2_on

  - platform: modbus_controller
    id: ${dim_id}_ch1_off
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH1 OFF"
    address: 210
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${dim_id}_ch1_off

  - platform: modbus_controller
    id: ${dim_id}_ch2_off
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH2 OFF"
    address: 211
    register_type: coil
    on_turn_on:
      - delay: 200ms
      - switch.turn_off: ${dim_id}_ch2_off



# ===================== Numbers (FC03/06/16 Holding) =====================
# Per-channel pairs: CH1/CH2 = +0/+1 offset
number:
  # --- Level 0..255 (400/401) ---
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH1 Level"
    address: 400
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider

  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH2 Level"
    address: 401
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 255
    step: 1
    mode: slider


  # --- Percent ×10 (0..1000) (440/441) ---
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH1 Percent ×10"
    address: 440
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 1000
    step: 10
    mode: slider
    unit_of_measurement: "x10 %"

  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH2 Percent ×10"
    address: 441
    register_type: holding
    value_type: U_WORD
    min_value: 0
    max_value: 1000
    step: 10
    mode: slider
    unit_of_measurement: "x10 %"

# ===================== Sensors (Holding RO) =====================
# Freq_x100 (Hz ×100) at 430/431 — expose as Hz with a multiply filter.
sensor:
  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH1 Mains Freq"
    address: 430
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: ${dim_id}
    name: "${dim_prefix} CH2 Mains Freq"
    address: 431
    register_type: holding
    value_type: U_WORD
    unit_of_measurement: "Hz"
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
